---

name: Gatsby

on:
  push:
    branches:
      - master
      - actions # remove after finished testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Get nvm version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
        working-directory: master

      - name: Setup node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: master

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: yarn install --frozen-lockfile
        working-directory: master

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            master/public
            master/.cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - run: yarn build
        working-directory: master

      - name: Check out pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clean directory
        run: rm -rf *
        working-directory: master

      - run: mv public/* ../gh-pages
        working-directory: master

      - name: commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: gh-pages
